export default {
  LOGIN_START: "LOGIN_START",
  LOGIN_OKAY: "LOGIN_OKAY",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_START: "REGISTER_START",
  REGISTER_OKAY: "REGISTER_OKAY",
  REGISTER_FAIL: "REGISTER_FAIL",
  CLEAR_AUTH_ERROR: "CLEAR_AUTH_ERROR",
  LOGOUT: "LOGOUT",
  GET_CURRENT_MEDITATION: "GET_CURRENT_MEDITATION",
  GET_CURRENT_MEDITATION_ERROR: "GET_CURRENT_MEDITATION_ERROR",
  UPDATE_MEDITATION: "UPDATE_MEDITATION"
};
